export const DEPENDENCY_RULES = [
  {
    key: 'front-to-back',
    label: 'Front to Back',
    kind: 'identity',
    match: ['frontline', 'teamfight', 'control'],
    needs: ['Frontline', 'DPS continuo', 'Peel'],
    wants: ['Engage'],
    avoids: ['Splitpush'],
    evidence: ['Shen', 'Jinx', 'Taric'],
    detail: 'La estructura frontal necesita aguantar mientras el carry pega con seguridad.',
  },
  {
    key: 'protect-carry',
    label: 'Protect Carry',
    kind: 'identity',
    match: ['protect', 'frontline', 'control'],
    needs: ['Frontline', 'Peel', 'Escalado'],
    wants: ['Teamfight'],
    avoids: ['Dive'],
    evidence: ['Taric', 'Jinx', 'Orianna'],
    detail: 'El carry necesita espacio, peel y tiempo para ganar la pelea.',
  },
  {
    key: 'pick',
    label: 'Pick',
    kind: 'identity',
    match: ['pick', 'engage', 'mobility'],
    needs: ['Visión', 'Engage', 'Burst'],
    wants: ['Control', 'Rotaciones'],
    avoids: ['Teamfight largo'],
    evidence: ['Vi', 'Nautilus', 'Ahri'],
    detail: 'El plan de pick necesita ver antes de golpear y cerrar rápido.',
  },
  {
    key: 'poke',
    label: 'Poke',
    kind: 'identity',
    match: ['poke', 'control', 'objective'],
    needs: ['Rango', 'Visión', 'Waveclear'],
    wants: ['Asedio'],
    avoids: ['Dive frontal'],
    evidence: ['Orianna', 'Xerath', 'Jayce'],
    detail: 'El poke necesita espacio para desgastar antes de entrar.',
  },
  {
    key: 'splitpush',
    label: 'Splitpush',
    kind: 'identity',
    match: ['splitpush', 'mobility', 'damage'],
    needs: ['Side lanes', 'Movilidad', 'Presión'],
    wants: ['Visión'],
    avoids: ['5v5 frontal'],
    evidence: ['Shen', 'Fiora', 'Tryndamere'],
    detail: 'El splitpush necesita laterales libres y presión constante en mapa.',
  },
  {
    key: 'double-engage',
    label: 'Double Engage',
    kind: 'pattern',
    match: ['engage', 'teamfight'],
    needs: ['2 iniciadores', 'Follow-up'],
    wants: ['Control'],
    avoids: ['Falta daño'],
    evidence: ['Wukong', 'Vi'],
    detail: 'Dos fuentes de entrada dan más seguridad al iniciar la pelea.',
  },
  {
    key: 'protect-hypercarry',
    label: 'Protect Hypercarry',
    kind: 'pattern',
    match: ['protect', 'frontline', 'control', 'scaling'],
    needs: ['Frontline', 'Peel', 'Late Carry'],
    wants: ['Escalado'],
    avoids: ['All-in temprano'],
    evidence: ['Jinx', 'Taric', 'Shen'],
    detail: 'Todo gira alrededor del hiper-carry y del tiempo para protegerlo.',
  },
  {
    key: 'heavy-pick',
    label: 'Heavy Pick',
    kind: 'pattern',
    match: ['pick', 'engage', 'mobility'],
    needs: ['Visión', 'Pick', 'Burst'],
    wants: ['Rotaciones'],
    avoids: ['5v5 largo'],
    evidence: ['Vi', 'Ahri', 'Nautilus'],
    detail: 'La composición convierte visión y ventanas cortas en asesinatos.',
  },
  {
    key: 'siege',
    label: 'Siege',
    kind: 'pattern',
    match: ['poke', 'control', 'objective'],
    needs: ['Rango', 'Waveclear', 'Presión'],
    wants: ['Objetivos'],
    avoids: ['Dive frontal'],
    evidence: ['Orianna', 'Xerath', 'Jayce'],
    detail: 'El siege necesita rango y limpieza para convertir presión en torres.',
  },
  {
    key: 'zone-control',
    label: 'Zone Control',
    kind: 'pattern',
    match: ['control', 'objective', 'poke'],
    needs: ['Control', 'Objetivos', 'Zonas'],
    wants: ['Visión'],
    avoids: ['Pelear desordenado'],
    evidence: ['Orianna', 'Taric', 'Ashe'],
    detail: 'Dominar áreas exige visión, control y orden alrededor de objetivos.',
  },
];
