export const PATTERN_RULES = [
  {
    key: 'double-engage',
    label: 'Double Engage',
    detail: 'Dos fuentes de entrada para iniciar peleas con más seguridad.',
    categories: ['engage', 'teamfight'],
    minHits: 2,
  },
  {
    key: 'double-frontline',
    label: 'Double Frontline',
    detail: 'Dos capas de primera línea para proteger al carry y al espacio frontal.',
    categories: ['frontline', 'teamfight', 'control'],
    minHits: 2,
  },
  {
    key: 'triple-carry',
    label: 'Triple Carry',
    detail: 'La composición concentra su amenaza en varios campeones de daño alto.',
    categories: ['damage', 'scaling', 'pick'],
    minHits: 3,
  },
  {
    key: 'protect-hypercarry',
    label: 'Protect Hypercarry',
    detail: 'El draft gira alrededor de un hiper-carry y de la protección alrededor de él.',
    categories: ['protect', 'frontline', 'control', 'scaling'],
    minHits: 3,
  },
  {
    key: 'heavy-pick',
    label: 'Heavy Pick',
    detail: 'La composición convierte visión y ventanas cortas en asesinatos.',
    categories: ['pick', 'engage', 'mobility'],
    minHits: 2,
  },
  {
    key: 'global-pressure',
    label: 'Global Pressure',
    detail: 'La presión global obliga a responder en varias zonas del mapa.',
    categories: ['pick', 'mobility', 'control'],
    minHits: 2,
  },
  {
    key: 'wombo-combo',
    label: 'Wombo Combo',
    detail: 'La pelea en área se resuelve con ultimates encadenadas.',
    categories: ['teamfight', 'engage', 'control'],
    minHits: 3,
  },
  {
    key: 'siege',
    label: 'Siege',
    detail: 'El equipo desgasta desde rango y transforma la presión en estructuras.',
    categories: ['poke', 'control', 'objective'],
    minHits: 2,
  },
  {
    key: 'zone-control',
    label: 'Zone Control',
    detail: 'La composición domina áreas y obliga a pelear en terreno favorable.',
    categories: ['control', 'objective', 'poke'],
    minHits: 2,
  },
];
